name: cfn_nag-updater

on: repository_dispatch

jobs:
  update_cfn_nag:
    name: Update cfn_nag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Checkout cfn_nag repo
        uses: actions/checkout@v2
        with:
          repository: stelligent/cfn_nag
          path: cfn_nag
      - name: Setup cfn_nag repo
        run: |
          git -C cfn_nag fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git config --global user.email "homebrew-tap@stelligent.com"
          git config --global user.name "stelligent-homebrew-tap-updater"
      - name: Update versions and sha256
        id: update
        run: |
          bash ./.github/scripts/update_cfn_nag_formula_version.sh
          rm -rf cfn_nag
        env:
          ORG: stelligent
      - name: Commit
        run: |
          git diff
          git add .
          git commit --allow-empty -m "auto-update cfn_nag version (${{ steps.update.outputs.cfn_nag_version }}) and sha256"
          git push
